import { useState } from "react";
import { helloThing } from "./api";

//Generated by AI for testing for now, including the step by step run me down

function App() {
  const [input, setInput] = useState("");
  const [output, setOutput] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  async function handleSubmit() {
    setLoading(true);
    setError(null);
    setOutput(null);

    try {
      const data = await helloThing(input);
      setOutput(data.output);
    } catch (err) {
      setError("Failed to fetch from backend");
    } finally {
      setLoading(false);
    }
  }

  return (
    <main style={{ padding: "2rem", maxWidth: 400 }}>
      <h1>Hello Thing</h1>

      <input
        value={input}
        onChange={(e) => setInput(e.target.value)}
        placeholder="Enter a thing"
        style={{ width: "100%", marginBottom: "1rem" }}
      />

      <button onClick={handleSubmit} disabled={loading}>
        {loading ? "Loading..." : "Say hello"}
      </button>

      {output && <p><strong>{output}</strong></p>}
      {error && <p style={{ color: "red" }}>{error}</p>}
    </main>
  );
}

export default App;
